# Generated by Django 3.1.7 on 2021-04-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaulter', '0002_remove_safe_date_modified_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safe',
            name='email',
        ),
    ]
