# Generated by Django 3.1.7 on 2021-04-02 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaulter', '0003_remove_safe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='date_modified_last',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='safe',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safe',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safe',
            name='pwned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safe',
            name='service',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safe',
            name='vaultername',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
