# Generated by Django 3.1.7 on 2021-04-04 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaulter', '0004_auto_20210402_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safe',
            name='vaultername',
        ),
        migrations.AddField(
            model_name='safe',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
